# Generated by Django 6.0 on 2026-01-11 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.CharField(default='Manhã: 07:00 às 12:00', max_length=100, verbose_name='Horário')),
            ],
            options={
                'verbose_name': 'Configuração de Agendamento',
                'verbose_name_plural': 'Configurações de Agendamento',
                'db_table': 'booking_config',
            },
        ),
        migrations.CreateModel(
            name='BusinessConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Julia Ellen Nails', max_length=100, verbose_name='Nome do Site')),
                ('phone_display', models.CharField(help_text='Ex: (81) 99999-9999', max_length=20, verbose_name='Telefone para Exibição')),
                ('whatsapp_number', models.CharField(help_text='Apenas números. Ex: 5581999999999', max_length=20, verbose_name='Número do WhatsApp')),
                ('instagram_handle', models.CharField(help_text='Sem o @. Ex: juliaellen.nails', max_length=50, verbose_name='Instagram')),
                ('address', models.CharField(default='Cosme Damião - Camaragibe', max_length=200, verbose_name='Endereço')),
                ('about_image', models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='Imagem Sobre')),
                ('about_text_p1', models.TextField(verbose_name='Sobre - Parágrafo 1')),
                ('about_text_p2', models.TextField(blank=True, verbose_name='Sobre - Parágrafo 2')),
                ('opening_days', models.CharField(default='Segunda a Sábado', max_length=50, verbose_name='Dias de Funcionamento')),
                ('opening_hours', models.CharField(default='07:00 às 18:00', max_length=50, verbose_name='Horário de Funcionamento')),
            ],
            options={
                'verbose_name': 'Configuração do Site',
                'verbose_name_plural': 'Configurações do Site',
                'db_table': 'business_config',
            },
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Texto alt da imagem', max_length=100, verbose_name='Título')),
                ('image', models.ImageField(upload_to='portfolio/', verbose_name='Imagem')),
            ],
            options={
                'verbose_name': 'Item de Portfólio',
                'verbose_name_plural': 'Itens de Portfólio',
                'db_table': 'portfolio_items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('description', models.TextField(max_length=200, verbose_name='Descrição')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Preço')),
                ('icon', models.CharField(choices=[('fa-hand-sparkles', 'Mão com Brilho'), ('fa-gem', 'Diamante'), ('fa-paint-brush', 'Pincel'), ('fa-spa', 'Flor de Lótus'), ('fa-seedling', 'Muda de Planta'), ('fa-heart', 'Coração'), ('fa-star', 'Estrela'), ('fa-magic', 'Varinha Mágica')], default='fa-hand-sparkles', max_length=50, verbose_name='Ícone')),
                ('is_sale', models.BooleanField(default=False, verbose_name='Destacar como Promoção?')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Destacar como Popular?')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
                'db_table': 'services',
                'ordering': ['-created_at'],
            },
        ),
    ]
