# Generated by Django 6.0 on 2026-01-11 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_service_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessconfig',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='hero/', verbose_name='Imagem Hero'),
        ),
    ]
