# Generated by Django 6.0 on 2026-01-11 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_businessconfig_hero_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Data e Hora')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP')),
                ('page', models.CharField(default='Home', max_length=100, verbose_name='Página Visitada')),
            ],
            options={
                'verbose_name': 'Visita',
                'verbose_name_plural': 'Contador de Visitas',
                'ordering': ['-timestamp'],
            },
        ),
    ]
