# Generated by Django 6.0 on 2026-01-16 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_visit'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Data de início')),
                ('end_date', models.DateField(verbose_name='Data de término')),
                ('reason', models.CharField(blank=True, max_length=100, verbose_name='Motivo')),
            ],
            options={
                'verbose_name': 'Data Bloqueada',
                'verbose_name_plural': 'Datas Bloqueadas',
                'db_table': 'blocked_dates',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('only_current_month', models.BooleanField(default=False, help_text='Se marcado, os agendamentos só poderão ser feitos dentro do mês corrente.', verbose_name='Permitir agendamentos apenas no mês atual?')),
                ('max_days_ahead', models.PositiveIntegerField(default=30, help_text="Usado quando 'Permitir agendamentos apenas no mês atual?' não está marcado.", verbose_name='Quantos dias à frente os agendamentos são permitidos?')),
                ('works_sunday', models.BooleanField(default=False, verbose_name='Domingo')),
                ('works_monday', models.BooleanField(default=True, verbose_name='Segunda-feira')),
                ('works_tuesday', models.BooleanField(default=True, verbose_name='Terça-feira')),
                ('works_wednesday', models.BooleanField(default=True, verbose_name='Quarta-feira')),
                ('works_thursday', models.BooleanField(default=True, verbose_name='Quinta-feira')),
                ('works_friday', models.BooleanField(default=True, verbose_name='Sexta-feira')),
                ('works_saturday', models.BooleanField(default=True, verbose_name='Sábado')),
            ],
            options={
                'verbose_name': 'Configurações de Agendamento',
                'verbose_name_plural': 'Configurações de Agendamento',
                'db_table': 'schedule_config',
            },
        ),
    ]
